### ISSUE TITLE
Adding Open Graph scraping

### ISSUE THREAD

**Issue by kasperwelbers** [JBGruber/paperboy#18]
Hi Johannes,

I was using paperboy in teaching (which worked really great!) and came across some cases where students mostly just needed a headline, and possible short snippet. Paperboy works great for this, but I thought it might be nice if it supported only looking up meta tags, like Open Graph properties, since this only requires HEAD requests. 

So my question was whether you think it would make sense to include this in Paperboy (or maybe it's already there and I just haven't found it). So something like a pb_deliver_meta function that simply gets the head for every URL and returns all meta tags with a property (like og: and twitter:)

**Comment by JBGruber** [comment]
Hi Kasper,

glad you can make use of this in teaching!

The idea of head requests sounds pretty cool, but I'm not sure it works in practice. I had a quick look at the underlying `curl` package and apparently this is how you make the requests:

``` r
library(curl)
# regular request
h <- new_handle()
req <- curl_fetch_memory("https://www.volkskrant.nl/klimaattop/vn-top-in-dubai-bereikt-historisch-akkoord-over-wegbewegen-van-fossiele-brandstoffen~b6ce433e/", handle = h)
object.size(rawToChar(req$content))
#> 191880 bytes

# head request
handle_setopt(h, nobody = TRUE)
req_head <- curl_fetch_memory("https://www.volkskrant.nl/klimaattop/vn-top-in-dubai-bereikt-historisch-akkoord-over-wegbewegen-van-fossiele-brandstoffen~b6ce433e/", handle = h)
object.size(rawToChar(req_head$content)) # body is empty
#> 112 bytes

# this is how the headers look
rawToChar(req_head$headers)
#> [1] "HTTP/2 200 \r\ncontent-type: text/html;charset=UTF-8\r\nx-correlation-id: b015290af46d489aa4e14a8ee39ff3bb\r\ncache-control: public, must-revalidate, max-age=120\r\nexpires: Wed, 13 Dec 2023 09:27:52 GMT\r\nlast-modified: Wed, 13 Dec 2023 09:25:52 GMT\r\nx-content-type-options: nosniff\r\nx-xss-protection: 1; mode=block\r\nx-frame-options: SAMEORIGIN\r\ncontent-encoding: gzip\r\ncontent-language: en\r\ncontent-length: 35334\r\ndate: Wed, 13 Dec 2023 09:27:00 GMT\r\nvary: Accept-Encoding\r\nstrict-transport-security: max-age=31536000 ; includeSubDomains ; preload\r\nlink: <https://images0.persgroep.net>; rel=preconnect;\r\ncontent-security-policy: default-src https: blob:; script-src 'unsafe-inline' 'unsafe-eval' https:; style-src 'unsafe-inline' https:; img-src data: https: blob: android-webview android-webview-video-poster:; font-src data: https:; connect-src *; media-src https: data: blob:; worker-src https: blob:; upgrade-insecure-requests; report-uri https://depersgroep.report-uri.io/r/default/csp/enforce\r\npermissions-policy: ch-ua-model=*,ch-ua-platform-version=*\r\naccept-ch: sec-ch-ua-model,sec-ch-ua-platform-version\r\n\r\n"
```

<sup>Created on 2023-12-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
 This would be easy to implement on the download site and could be handed to a special open graph parsers. But the response does not seem to contain the necessary tags.
 
 I double-check with `curl` from the command line to see if I get anything else:
 
 ```
$ curl -s --head -X GET https://www.volkskrant.nl/klimaattop/vn-top-in-dubai-bereikt-historisch-akkoord-over-wegbewegen-van-fossiele-brandstoffen~b6ce433e/
HTTP/2 200 
content-type: text/html;charset=UTF-8
x-correlation-id: b015290af46d489aa4e14a8ee39ff3bb
cache-control: public, must-revalidate, max-age=120
expires: Wed, 13 Dec 2023 09:27:52 GMT
last-modified: Wed, 13 Dec 2023 09:25:52 GMT
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-frame-options: SAMEORIGIN
content-language: en
date: Wed, 13 Dec 2023 09:25:52 GMT
set-cookie: enableSentry_v1=false; expires=Thu, 12-Dec-2024 09:25:52 GMT; secure
strict-transport-security: max-age=31536000 ; includeSubDomains ; preload
link: <https://images0.persgroep.net>; rel=preconnect;
content-security-policy: default-src https: blob:; script-src 'unsafe-inline' 'unsafe-eval' https:; style-src 'unsafe-inline' https:; img-src data: https: blob: android-webview android-webview-video-poster:; font-src data: https:; connect-src *; media-src https: data: blob:; worker-src https: blob:; upgrade-insecure-requests; report-uri https://depersgroep.report-uri.io/r/default/csp/enforce
permissions-policy: ch-ua-model=*,ch-ua-platform-version=*
accept-ch: sec-ch-ua-model,sec-ch-ua-platform-version
```
I checked with a few other websites, which also produced nothing of interest. Maybe I misunderstand what you mean by HEAD requests?

**Comment by kasperwelbers** [comment]
Oh, sorry, it seems I misunderstood the Open Graph protocol.

As I understood it, it's mainly intended so that you can control what a webpage looks like when someone shares it somewhere, e.g., on Twitter. So I just assumed that it would include these meta properties in the headers as well, so that whenever a social media platform needs to (re)retrieve the open graph data, it doesn't need to get the full body.

But indeed, it appears that the open graph properties are only included in the <head> section (which is part of the content), and not in the headers (which is what you get with a HEAD request). 

So yeah, that kinda ruins the idea :(

**Comment by JBGruber** [comment]
It sounded really cool, but yeah, the meta tags are at the start/head of the content, not in the headers, and I don't think there is a fast and reliable way to extract just that (I thought about only reading X bytes, but sometimes there is random CSS or JS before the tags). I also often don't use them, since many website insert information into the Open Graph fields that is rather useless (e.g., add the name of the outlet to the headline).
