### ISSUE TITLE
parsing script type="application/ld+json"

### ISSUE THREAD

**Issue by schochastics** [JBGruber/paperboy#25]
@JBGruber  In #24, I noticed that many news pages have most of the content ready to parse as json hidden in a script tag like this:
`<script type="application/ld+json"><<json metadata>></script>`

I first thought it is only german news sites but I also found it elsewhere. have you noticed this before? If so, is it bad to rely on it (I use it now for all german sites)?

**Comment by JBGruber** [comment]
I used it for some scrapers that were running reliable for months. Like:

https://github.com/JBGruber/paperboy/blob/main/R%2Fdeliver_joe_ie.R
https://github.com/JBGruber/paperboy/blob/main/R%2Fdeliver_irishtimes_com.R
https://github.com/JBGruber/paperboy/blob/main/R%2Fdeliver_blesk_cz.R

At some point I wanted to look into applying this more broadly. But the json structure is always slightly different as far as I remember. And often it's not the first json on the site that has the right data.

**Comment by schochastics** [comment]
thanks. I will use it if possible and one could refactor later if there is a clear pattern emerging for a large group of news sides
